% function acq_settings = util_get_si_acq_parameters(app)
global acq_settings
cmd = 'assignin("caller","hSIcopy",hSI);';
evalin('base',cmd);
img_dim=max(hSIcopy.hRoiManager.imagingFovUm)-min(hSIcopy.hRoiManager.imagingFovUm);
acq_settings = struct('pixelsPerLine', hSIcopy.hRoiManager.pixelsPerLine,...
'linesPerFrame', hSIcopy.hRoiManager.linesPerFrame,...
'scanZoomFactor', hSIcopy.hRoiManager.scanZoomFactor,...
'scanRotation', hSIcopy.hRoiManager.scanRotation,...
'scanFrameRate', hSIcopy.hRoiManager.scanFrameRate,...
'scanFramePeriod', hSIcopy.hRoiManager.scanFramePeriod,...
'linePeriod', hSIcopy.hRoiManager.linePeriod,...
'imagingFovSizeUm_nrows', img_dim(1),...
'imagingFovSizeUm_ncols', img_dim(2),...
'axesPosition_x',hSIcopy.hMotors.axesPosition(1),...
'axesPosition_y',hSIcopy.hMotors.axesPosition(2),...
'axesPosition_z',hSIcopy.hMotors.axesPosition(3),...
'samplePosition_x',hSIcopy.hMotors.samplePosition(1),...
'samplePosition_y',hSIcopy.hMotors.samplePosition(2),...
'samplePosition_z',hSIcopy.hMotors.samplePosition(3));

assignin("caller","acq_settings",acq_settings)