% function acq_settings = util_get_si_acq_parameters(app)
global acq_settings
cmd = 'assignin("caller","hSIcopy",hSI);';
evalin('base',cmd);
img_dim=max(hSIcopy.hRoiManager.imagingFovUm)-min(hSIcopy.hRoiManager.imagingFovUm);
acq_settings = struct('pixelsPerLine', hSIcopy.hRoiManager.pixelsPerLine,...
'linesPerFrame', hSIcopy.hRoiManager.linesPerFrame,...
'scanZoomFactor', hSIcopy.hRoiManager.scanZoomFactor,...
'scanRotation', hSIcopy.hRoiManager.scanRotation,...
'scanFrameRate', hSIcopy.hRoiManager.scanFrameRate,...
'scanFramePeriod', hSIcopy.hRoiManager.scanFramePeriod,...
'linePeriod', hSIcopy.hRoiManager.linePeriod,...
'imagingFovSizeUm_nrows', img_dim(1),...
'imagingFovSizeUm_ncols', img_dim(2),...
'axesPosition_x',hSIcopy.hMotors.axesPosition(1),...
'axesPosition_y',hSIcopy.hMotors.axesPosition(2),...
'axesPosition_z',hSIcopy.hMotors.axesPosition(3),...
'samplePosition_x',hSIcopy.hMotors.samplePosition(1),...
'samplePosition_y',hSIcopy.hMotors.samplePosition(2),...
'samplePosition_z',hSIcopy.hMotors.samplePosition(3),...
'beam1_power',hSIcopy.hBeams.powers(1),...
'beam2_power',NaN);

%%
if numel(hSIcopy.hBeams.powers)>1
    acq_settings.beam2_power = hSIcopy.hBeams.powers(2);
end

%% check if stack mode is enabled and append variables accordingly
stackManager = hSIcopy.hStackManager;
if stackManager.enable
    num_slices = stackManager.actualNumSlices;
    step_size = stackManager.actualStackZStepSize;
    z_start = stackManager.stackZStartPos;
    z_end = stackManager.stackZEndPos;
    frames_per_slice = stackManager.framesPerSlice;
else
    num_slices=nan;
    step_size=nan;
    z_start=nan;
    z_end = nan;
    frames_per_slice = nan;
end

acq_settings.num_slices = num_slices;
acq_settings.step_size = num_slices;
acq_settings.frames_per_slice = num_slices;
acq_settings.z_start = num_slices;
acq_settings.z_end = num_slices;


assignin("caller","acq_settings",acq_settings)