function [this_session,status] = util_log_session(app)
%UTIL_LOG_SESSION Summary of this function goes here
%%   Gather session data to log
if ~numel(app.SessionDescription.Value{:});app.SessionDescription.Value={'None'};end
this_session = struct(...
    'session_id',app.SESSION_ID,...
    'acquisition_id',app.ACQ_ID,...
    'project_id',app.PROJECT_ID,...
    'subject_id',app.SUBJECT_ID,...
    'condition',app.CONDITION,...
    'fov',app.FOV,...
    'timepoint',app.TIMEPOINT,...,
    'anesthesia',app.ANESTHESIA,...
    'labeling',app.LABELING,...
    'pharmacology',app.PHARMACOL,...
    'description',app.SessionDescription.Value,...
    'acquisition_mode',app.DatatypeDropDown.Value,...
	'keep_session_for_analysis',{'TBD'},...
	'comments',{'None'},...
    'path_to_data',app.PATH_TO_DATA_REL);

% if ~numel(this_session.description);this_session.description={'None'};end


this_session_table=struct2table(this_session,'AsArray',true);

%% load file if exists, create otherwise
path_to_sessions = fullfile(app.PROJECT_ROOT_DIR,'sessions.csv');
if isfile(path_to_sessions)
    sessions = readtable(path_to_sessions);
    acq_ids = sessions.acquisition_id;
    if ~ismember(acq_ids,this_session.acquisition_id)
        sessions = [sessions;this_session_table];
        fprintf('\n\tUpdating session table\n')        
        writetable(sessions,path_to_sessions)
    end %do nothing otherwise, session already in table
    
else
    fprintf('\n\tCreating session table\n')
    writetable(this_session_table,path_to_sessions);
end
status = 1;

end

