function subject = util_get_subject(app)
subject =  struct('id',app.AnimalIDTextArea.Value{1},...
    'species', app.SpeciesDropDown.Value,'genotype',app.GenotypeDropDown.Value,...
    'strain',app.StrainDropDown.Value,...
    'sex',app.SexDropDown.Value,'weight',...
    app.WeightgrSpinner.Value,'dob',app.DOBDatePicker_2.Value,...
    'surgery',app.SurgeryDropDown.Value,'hemisphere',app.HemisphereDropDown.Value,...
    'surgery_date',app.SurgerydateDatePicker.Value,'Virus',app.VirusDropDown.Value,...
    'virus_injection_date',app.InjectiondateDatePicker.Value,...
    'description',app.subject_description.Value);
end